### ISSUE TITLE
Most Iterable extensions don't work with implicit-casts: false

### ISSUE THREAD

**Issue by kuhnroyal** [felixblaschke/supercharged#2]
As far as I understand, `implicit-casts: false` will become the default with NNBD (https://github.com/dart-lang/sdk/issues/31410#issuecomment-510683629).

Currently most extensions fail with this set because the resulting generic types are not casted.
The solution is to also specify the type parameters on the extension functions.
For example change `Map<K, List<V>> groupBy` to `Map<K, List<V>> groupBy<K, V>`.

```dart
extension Iterable_<T, K, V> on Iterable<T> {
  Map<K, List<V>> groupBy<K, V>(K Function(T element) keySelector,
      {V Function(T element) valueTransform}) {
    ArgumentError.checkNotNull(keySelector);

    if (valueTransform == null) {
      valueTransform = (element) => element as V;
    }

    Map<K, List<V>> map = {};

    this.forEach((element) {
      var key = keySelector(element);

      if (!map.containsKey(key)) {
        map[key] = [];
      }
      map[key].add(valueTransform(element));
    });

    return map;
  }
}
```

**Comment by felixblaschke** [comment]
Thank you for the information. I will look into that topic and try to fix all code while having `implicit-casts: false`

**Comment by felixblaschke** [comment]
I fixed all analytic errors that happend when having `implicit-casts: false`. Changes are pushed to `master` branch. Do you have the opportunity to verify it?

**Comment by kuhnroyal** [comment]
I am afraid this does not solve the problem and I may not have explained it correctly.
I also don't think the changes in https://github.com/felixblaschke/supercharged/commit/74ff7272496dedd84751218fdfdb108fd7354cbc are needed.

The problem may only occur with the `List<T>` to `Map<K, V>` extensions ` groupBy` and `associate*`.

Your extension `Iterable_<T, K, V>` declares 3 generics types but only one is known from the source iterable (`T`). `K` and `V` are actually unknown, and if those can not be inferred the compiler will just cast it (with `implicit-casts: true`).

Of course one can always cast the results of `groupBy` for example but instead the function should have the `K` and `V` generic type arguments to help the compiler infer the resulting type `groupBy<K, V>`.

**Comment by felixblaschke** [comment]
I used the past time to re-read everything about generics in dart and experimented a bit. Now I have a better understanding on what's going on.

I learned that `this.` is obiviously unnecessary and causes problems (dart loses generics type information when using `this`).

I made some changes 700ea4a2720069f8bef6c8059ae35806aede4815
Can you verify that it's the way to go?

**Comment by kuhnroyal** [comment]
This looks good, thanks!

Now we just need a way of calling extensions function on null receivers in Dart for more Kotlin magic. :)

**Comment by felixblaschke** [comment]
Great! Thank you for your help :-)
